project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    fontsize: 0.9em
    linestretch: 1.7



